name: CI Pipeline

on:
  pull_request:
    branches:
      - dev

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  setup_dotnet:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.101'

  restore_dependencies:
    runs-on: ubuntu-latest
    needs: setup_dotnet

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.101'
        
    - name: Restore .NET dependencies
      run: dotnet restore

  build:
    runs-on: ubuntu-latest
    needs: restore_dependencies

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.101'
        
    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build .NET project
      run: dotnet build --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.101'
        
    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build .NET project
      run: dotnet build --configuration Release --no-restore

    - name: Run .NET tests
      run: dotnet test --no-restore --verbosity normal
